name = "Midlegram"


[assets]
src = [
    "src/**/*.java"
]
res = [
    "res/*:.",
]
manifest = "MANIFEST.MF"


[build]
output_dir = "build"


[libs]
[libs.nokia-platform-libs]
glob = "lib/**.jar"
include = false
